### ISSUE TITLE
How do you dispatch API calls based on version?

### ISSUE THREAD

**Issue by dotboris** [sticksnleaves/versionary#3]
After reading the documentation, I can't figure out how to have different handlers for different API versions.

Let's say that I have two version in my api: `v1` and `v2`. How do I make it so that I can one handler run for `v1` requests and another for `v2` requests? I'm not very proficient with Plug, so this could be something basic that I'm missing.

Perhaps this use case should be documented.

**Comment by elpic** [comment]
@dotboris I just created a PR with an example (and some changes) to support multiple versions (https://github.com/sticksnleaves/versionary/pull/4)

**Comment by anthonator** [comment]
Closed by #4
